version: '3.8'

services:
  web:
    build: .
    command: gunicorn shop_project.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # ФІКС 1: Додали спільний том для збору статики
    expose:
      - "8000"                          # ФІКС 2: Закрили порт 8000 від світу, він доступний лише для Nginx всередині мережі Docker
    environment:
      - DEBUG=False
      - SECRET_KEY=production-secret-key-replace-me
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - USE_REDIS=True
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"                         # Прокидаємо 80 порт назовні
    volumes:
      - ./nginx:/etc/nginx/conf.d       # Конфіг із лімітером, який створить скрипт
      - static_volume:/app/staticfiles  # Читаємо статику з того самого тому
    depends_on:
      - web

volumes:
  redis_data:
  static_volume:                        # Спільний том для Django та Nginx
