version: '3.8'

services:
  web:
    build: .
    command: gunicorn shop_project.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=production-secret-key-replace-me
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - USE_REDIS=True
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"                         # Пробрасываем 80 порт наружу в мир
    volumes:
      - ./nginx:/etc/nginx/conf.d       # Прокидываем конфиг, который создали на Шаге 2
      - static_volume:/app/staticfiles  # Монтируем тот же том со статикой для чтения Nginx
    depends_on:
      - web

volumes:
  redis_data:
  static_volume:
